Gh scraping
Clanhouse/gh-robber pull request #31
Opened 2022-02-15 19:10 UTC by WojtekS-dev

Changed the database structure - now users and repos are in separate tables with many-to-many connection between them
Added functions for scraping GH
Refactored filtering in API to work with new database

2022-02-18 17:22 UTC, PK109 commented on backend/env.txt
> +SQLALCHEMY_DATABASE_URI=mysql+pymysql://user_dev:userdev@localhost/gh_db?charset=utf8mb4
This part shall not be changed

2022-03-24 12:16 UTC, orzeech requested changes

2022-03-24 12:16 UTC, orzeech commented on backend/app/GH_API_handling.py
> +        print(f"User {usrname} has been found in database")
use logging library instead of printing out

2022-03-24 12:16 UTC, orzeech commented on backend/app/GH_API_handling.py
> +                    # db.session.add(gh_user)
do not commit commented-out code

2022-03-24 12:16 UTC, orzeech commented on backend/app/GH_API_handling.py
> +                return "something went wrong in update_repo"
log the error better

2022-03-24 12:16 UTC, orzeech commented on backend/app/GH_API_handling.py
> +            # adds contibutors - turned off to prevent infinite loop
add a task to do this

2022-03-24 12:16 UTC, orzeech commented on backend/env.txt
> +SQLALCHEMY_DATABASE_URI=mysql+pymysql://user_dev:userdev@localhost/gh_db?charset=utf8mb4
these should probably be kept as is

2022-03-29 18:30 UTC, orzeech approved these changes

2022-03-29 18:30 UTC, merged